export const SEQUELIZE = 'SEQUELIZE';
export const PETS_REPOSITORY = 'PETS_REPOSITORY';
export const BREEDS_REPOSITORY = 'BREEDS_REPOSITORY';
export const SUBBREEDS_REPOSITORY = 'SUBBREEDS_REPOSITORY';